apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: identity-serviceaccount
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true

      containers:
      - name: identity
        image: microshop.azurecr.io/identity.service:1.0.27
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICEBUS
          - name: ServiceSettings__KeyVaultName
            value: microshop
          - name: IdentitySettings__PathBase
            value: /identity-svc
          - name: IdentitySettings__CertificateCerFilePath
            value: "/certificates/certificate.crt"
          - name: IdentitySettings__CertificateKeyFilePath
            value: "/certificates/certificate.key"
          - name: ServiceSettings__Authority
            value: https://microshop.westus2.cloudapp.azure.com/identity-svc
          - name: IdentityServerSettings__Clients__0__RedirectUris__0
            value: "https://microshop.westus2.cloudapp.azure.com/authentication/login-callback"
          - name: IdentityServerSettings__Clients__0__RedirectUris__1
            value: "urn:ietf:wg:oauth:2.0:oob"
          - name: IdentityServerSettings__Clients__1__RedirectUris__0
            value: "https://microshop.westus2.cloudapp.azure.com/authentication/login-callback"
          - name: IdentityServerSettings__Clients__1__PostLogoutRedirectUris__0
            value: "https://microshop.westus2.cloudapp.azure.com/authentication/logout-callback"

        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
          - containerPort: 5002
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5002
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5002
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
          - name: certificate-volume
            mountPath: /certificates
          - name: dataprotection-volume
            mountPath: /app/keys
      volumes:
        - name: certificate-volume
          secret:
            secretName: signing-cert
            items:
              - key: tls.key
                path: certificate.key
              - key: tls.crt
                path: certificate.crt
        - name: dataprotection-volume
          persistentVolumeClaim:
            claimName: identity-dataprotection-pvc
  
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: ClusterIP
  selector:
    app: identity
  ports:
    - port: 80
      targetPort: 5002

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 12e3b28a-ca9b-4e24-ae54-3dcae90efa0d
  labels:
    azure.workload.identity/use: "true"
  name: identity-serviceaccount

