# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CICD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Github Tag Bump
      id: tag_bump
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 1.0.28
        DEFAULT_BUMP: patch
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.tag_bump.outputs.new_tag }}

  build-and-deploy:

    runs-on: ubuntu-latest
    needs: generate-version
    env:
      APP_NAME: microshop
      SERVICE_NAME: identity
      HELM_CHART_VERSION: 0.1.0
      
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Azure Login
      uses: Azure/login@v1
      with:
        # ClientId of the Azure Service principal created.
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        # TenantId of the Azure Service principal created.
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        # Azure subscriptionId
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
